[project]
name = "genesis-forge-wheeled-robot-goal-nav-example"
version = "0.1.0"
description = "A Genesis Forge example environment demonstrating a wheeled robot navigating to goal positions while avoiding obstacles."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "genesis-forge",
    "rsl-rl-lib~=5.0",
    "tensorboard",
]

[tool.uv.sources]
genesis-forge = { path = "../../" }
