[project]
name = "genesis-forge-basic-example"
version = "0.1.0"
description = "A basic locomotion training environment for the Go2 robot with Genesis Forge."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "genesis-forge",
    "rsl-rl-lib~=5.0",
    "tensorboard",
]

[tool.uv.sources]
genesis-forge = { path = "../../" }
